platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

image_resource:
  type: docker-image
  source: {repository: node}

inputs:
- name: src-brain

run:
  path: ./src-brain/build.sh
